server:
  port: 9300
spring:
  application:
    name: service-movies
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:MovieBD
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9500/eureka